<?php
/**
 * @file
 * A light-weight, customizable image gallery plugin for Drupal based on jQuery
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\flexslider\Entity\Flexslider;
use Symfony\Component\Validator\Constraints\True;

define("FLEXSLIDER_VERSION", \Drupal::config('flexslider.settings')->get('flexslider_version'));
define("FLEXSLIDER_DEBUG", \Drupal::config('flexslider.settings')->get('flexslider_debug'));

/**
 * Implements hook_libraries_info().
 */
function flexslider_libraries_info() {
  $libraries['flexslider'] = array(
    'name' => 'FlexSlider',
    'vendor url' => 'http://www.woothemes.com/flexslider/',
    'download url' => 'https://github.com/woothemes/FlexSlider',
    'version arguments' => array(
      'file' => 'jquery.flexslider-min.js',
      // jQuery FlexSlider v2.1
      'pattern' => '/jQuery FlexSlider v(\d+\.+\d+)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array(
        'jquery.flexslider-min.js',
      ),
      'css' => array(
        'flexslider.css',
      ),
    ),
    'integration files' => array(
      'flexslider' => array(
        'css' => array('assets/css/flexslider_img.css'),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_libraries_info_alter().
 */
function flexslider_libraries_info_alter(&$libraries) {
  $debug = FLEXSLIDER_DEBUG;
  if ($debug) {
    // Switch to the unminified version of the library
    if (isset($libraries['flexslider'])) {
      $libraries['flexslider']['files']['js'] = array(
        'jquery.flexslider.js',
      );
    }
  }

  // Add support for jQuery Easing module
  if (\Drupal::moduleHandler()->moduleExists('jqeasing')) {
    $libraries['flexslider']['dependencies'][] = 'easing (>=1.3)';
  }
}

/**
 * Implements hook_library_info_build().
 *
 * We also define FlexSlider through the core library callbacks
 */
function flexslider_library_info_build() {
  $libraries = [];

  $library_path = libraries_get_path('flexslider');
  if (strpos($library_path, '/') !== 0) {
    $library_path = '/' . $library_path;
  }

  $libraries['flexslider'] = array(
    'title' => 'FlexSlider',
    'remote' => 'http://flexslider.woothemes.com',
    'version' => FLEXSLIDER_VERSION,
    'license' => array(
      'name' => 'GNU-GPL-2.0-or-later',
      'url' => 'https://github.com/woothemes/FlexSlider/blob/master/LICENSE.md',
      'gpl-compatible' => TRUE,
    ),
    'dependencies' => array(
      'core/jquery',
      'core/drupal',
      'core/drupalSettings',
      'core/jquery.once',
    ),
    'js' => array(
      $library_path . '/jquery.flexslider-min.js' => array(
        'scope' => 'footer',
      ),
      'assets/js/flexslider.load.js' => array(
        'scope' => 'footer',
      ),
    ),
    'css' => array(
      'theme' => array(
        $library_path . '/flexslider.css' => array(
          'media' => 'screen',
        ),
        'assets/css/flexslider_img.css' => array(
          'media' => 'screen',
        ),
      ),
    ),
  );

  // Add support for jQuery Easing module
  if (\Drupal::moduleHandler()->moduleExists('jqeasing')) {
    // Using the jqeasing module
    $libraries['flexslider']['dependencies'][] = 'jqeasing.easing';
  }
  /*
  else {
    // Without the module
    $libraries['flexslider']['easing'] = [
      'remote' => 'https://github.com/gdsmith/jquery.easing',
      'license' => [
        'name' => 'MIT',
        'url' => 'http://www.opensource.org/licenses/mit-license.php',
        'gpl-compatible' => true,
      ],
      'version' => '1.3',
      'js' => [
        '/libraries/easing/jquery.easing.min.js'
      ],
      'dependencies' => [
        'core/jquery'
      ],
    ];
  }
  */
  return $libraries;
}

/**
 * Implements hook_library_info_alter().
 */
function flexslider_library_info_alter(&$libraries, $extension) {
  // Enable debug mode
  if (FLEXSLIDER_DEBUG) {
    if ($extension == 'flexslider' and isset($libraries['flexslider'])) {
      $libraries['flexslider/flexslider']['js'] = array(
        libraries_get_path('flexslider') . '/jquery.flexslider.js' => array(
          'scope' => 'footer',
        ),
      );
    }
  }
}

/**
 * Implements hook_help().
 */
function flexslider_help($route_name, RouteMatchInterface $route_match) {
  $vendor_link = \Drupal\Core\Link::fromTextAndUrl(t('FlexSlider documentation'), \Drupal\Core\Url::fromUri('http://www.woothemes.com/flexslider/'));
  $vendor_link = $vendor_link->toRenderable();
  $vendor_link['#attributes'] = array('target' => '_new');
  switch ($route_name) {
    case 'help.page.flexslider':
      return
        '<p>'
        . t('An <em>option set</em> defines exactly how a flexslider image gallery looks like on your site. '
          . 'It is a combination of <a href="@styles">image styles</a> for the various image sizes and FlexSlider library options.', array('@styles' => url('admin/config/media/image-styles'))) . '<br />'
        . t('For a full documentation of all options, refer to the official @docs.', array('@docs' => render($vendor_link)))
        . '</p>';
    case 'entity.flexslider.collection':
        return
            '<p>'
          . t('An <em>option set</em> defines exactly how a flexslider image gallery looks and behaves on your site.') . '<br />'
          . t('For a full documentation of all library options, refer to the official @docs.', array('@docs' => render($vendor_link)))
          . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function flexslider_theme() {
  return array(
    // Flexslider container
    'flexslider' => array(
      'variables' => array('items' => array(), 'settings' => array()),
      'file' => 'templates/flexslider.theme.inc',
    ),
    
    // Slide container
    'flexslider_list' => array(
      'variables' => array('items' => array(), 'settings' => array()),
      'file' => 'templates/flexslider.theme.inc',
    ),
    
    // Slide item
    'flexslider_list_item' => array(
      'variables' => array('item' => array(), 'settings' => array(), 'caption' => ''),
      'file' => 'templates/flexslider.theme.inc',
    ),
  );
}

/**
 * Gets an array of option sets suitable for using as select list options.
 *
 * @return array
 *   Array of optionset labels keyed by id
 */
function flexslider_optionset_list() {
  $optionsets = Flexslider::loadMultiple();
  $options = array();
  foreach ($optionsets as $name => $optionset) {
    $options[$name] = $optionset->label();
  }

  if (empty($options)) {
    $options[''] = t('No defined option sets');
  }
  return $options;
}

/**
 * This function returns an array of the required JavaScripts and settings for a flexslider
 * instance.
 *
 * @param string $id [optional]
 *  ID Attribute for FlexSlider container
 *
 * @param object|strong $optionset [optional]
 *  Option set to load or the machine name of an existing optionset
 *
 * @return array
 *   Array of asset attachments
 **/
function flexslider_add($id = NULL, $optionset = NULL) {

  $attached = [];

  // Check optionset value
  if (is_string($optionset)) {
    $name = $optionset;
    $optionset = Flexslider::load($name);
    if (empty($optionset)) {
      \Drupal::logger('flexslider')->warning('Invalid optionset name supplied to flexslider_add: @name', array('@name' => $name));
      return $attached;
    }
  }

  // Static array to remember which scripts are already attached.
  // @todo not currently in use
  $cache = &drupal_static(__FUNCTION__, array());

  $attached['library'][] = 'flexslider/flexslider';

  // If the ID or optionset aren't set, it is assumed the settings will be set
  // manually via the calling module/theme
  if (!empty($optionset) && !in_array($optionset->id(), $cache)) {
    $cache[] = $optionset->id();
    $attached['drupalSettings']['flexslider']['optionsets'] = array(
      $optionset->id() => $optionset->getOptions(TRUE),
    );
  }
  
  if (!empty($id)) {
    // JavaScript settings
    $attached['drupalSettings']['flexslider']['instances'] = array(
      $id => $optionset->id(),
    );

  }

  return $attached;
}

/**
 * List of all easing methods available from jQuery Easing v1.3
 */
function _flexslider_jqeasing_options() {
  return array(
    "jswing" => "jswing",
    "def" => "def",
    "easeInQuad" => "easeInQuad",
    "easeOutQuad" => "easeOutQuad",
    "easeInOutQuad" => "easeInOutQuad",
    "easeInCubic" => "easeInCubic",
    "easeOutCubic" => "easeOutCubic",
    "easeInOutCubic" => "easeInOutCubic",
    "easeInQuart" => "easeInQuart",
    "easeOutQuart" => "easeOutQuart",
    "easeInOutQuart" => "easeInOutQuart",
    "easeInQuint" => "easeInQuint",
    "easeOutQuint" => "easeOutQuint",
    "easeInOutQuint" => "easeInOutQuint",
    "easeInSine" => "easeInSine",
    "easeOutSine" => "easeOutSine",
    "easeInOutSine" => "easeInOutSine",
    "easeInExpo" => "easeInExpo",
    "easeOutExpo" => "easeOutExpo",
    "easeInOutExpo" => "easeInOutExpo",
    "easeInCirc" => "easeInCirc",
    "easeOutCirc" => "easeOutCirc",
    "easeInOutCirc" => "easeInOutCirc",
    "easeInElastic" => "easeInElastic",
    "easeOutElastic" => "easeOutElastic",
    "easeInOutElastic" => "easeInOutElastic",
    "easeInBack" => "easeInBack",
    "easeOutBack" => "easeOutBack",
    "easeInOutBack" => "easeInOutBack",
    "easeInBounce" => "easeInBounce",
    "easeOutBounce" => "easeOutBounce",
    "easeInOutBounce" => "easeInOutBounce",
  );
}