<?php
/**
 * @file
 * Flexslider_example module.
 *
 * @author Agnes Chisholm <amaria@chisholmtech.com>
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function flexslider_example_toolbar() {
  $items = array();

  // Load the menu.
  $fs_tree = Drupal::service('toolbar.menu_tree')->load('flexslider-example', new Drupal\Core\Menu\MenuTreeParameters());
  // Build the menu render array.
  $fs_menu = Drupal::service('toolbar.menu_tree')->build($fs_tree);

  $items['flexslider_examples'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('FlexSlider Examples'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => array(
        'title' => t('FlexSlider examples menu'),
        'class' => array('toolbar-icon', 'toolbar-icon-menu'),
      ),
    ),
    'tray' => array(
      '#heading' => t('FlexSlider examples menu'),
      'flexslider_example_menu' => $fs_menu,
    ),
    '#weight' => 99,
  );

  return $items;
}
