<?php

/**
 * @file
 * Describe the file
 *
 * @author Mathew Winstone <mwinstone@coldfrontlabs.ca>
 */

/**
 * Implements hook_menu().
 */
function flexslider_example_menu() {
  $items['flexslider-example'] = array(
    'title' => 'FlexSlider Example',
    'page callback' => 'flexslider_example_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_node_info().
 */
function flexslider_example_node_info() {
  $items = array(
    'flexslider_example' => array(
      'name' => t('FlexSlider Example'),
      'base' => 'node_content',
      'description' => t('Used for generating example FlexSlider implementations'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implements hook_field_default_fields().
 */
function flexslider_example_field_default_fields() {
  $fields = array();

  // Exported field: 'node-flexslider_example-field_flexslider_example_image'.
  $fields['node-flexslider_example-field_flexslider_example_image'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_flexslider_example_image',
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'locked' => '0',
      'module' => 'image',
      'settings' => array(
        'default_image' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'image',
    ),
    'field_instance' => array(
      'bundle' => 'flexslider_example',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'module' => 'image',
          'settings' => array(
            'image_link' => '',
            'image_style' => '',
          ),
          'type' => 'image',
          'weight' => '0',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_flexslider_example_image',
      'label' => 'FlexSlider Example Image',
      'required' => 0,
      'settings' => array(
        'alt_field' => 0,
        'default_image' => 0,
        'file_directory' => 'flexslider_example',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '',
        'max_resolution' => '',
        'min_resolution' => '',
        'title_field' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'image',
        'settings' => array(
          'preview_image_style' => 'thumbnail',
          'progress_indicator' => 'throbber',
        ),
        'type' => 'image_image',
        'weight' => '-4',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('FlexSlider Example Image');

  return $fields;
}

/**
 * Sample implementations of FlexSlider
 */
function flexslider_example_page() {
  // Prepare slider content
  
  // Basic Slider
  // @todo
}


function _flexslider_example_basic_slider() {
  
}