<?php
/**
 * @file
 * Contains \Drupal\flexslider\FlexsliderDefaults.
 * @author Agnes Chisholm <amaria@66428.no-reply.drupal.org>
 */

namespace Drupal\flexslider;

class FlexsliderDefaults {

  /**
   * Returns default flexslider library options.
   */
  public static function defaultOptions() {
    return [
      'namespace'           =>	'flex-',	          // String Prefix string attached to the classes of all elements generated by the plugin.
      'selector'               => '.slides > li',	  // Selector Must match a simple pattern. '{container} > {slide}'.
      'animation'             =>	'fade',            // String Controls the animation type, "fade" or "slide".
      'easing'                  => 'swing',          // String Determines the easing method used in jQuery transitions.
      'direction'               =>	'horizontal',	  // String Controls the animation direction, "horizontal" or "vertical"
      'reverse'                 =>	false,	          // Boolean Reverse the animation direction.
      'animationLoop'       =>	true,	            // Boolean Gives the slider a seamless infinite loop.
      'smoothHeight'        => false,	          // Boolean Animate the height of the slider smoothly for slides of varying height.
      'startAt'                  =>	0,	                // Number The starting slide for the slider, in array notation.
      'slideshow'              => true,	            // Boolean Setup a slideshow for the slider to animate automatically.
      'slideshowSpeed'      =>	7000,            //	Number Set the speed of the slideshow cycling, in milliseconds
      'animationSpeed'      =>	600,	            // Number Set the speed of animations, in milliseconds
      'initDelay'	               => 0,	                // Number Set an initialization delay, in milliseconds
      'randomize'	             => false,            //	Boolean Randomize slide order, on load
      'pauseOnAction'       =>	true,	            // Boolean Pause the slideshow when interacting with control elements.
      'pauseOnHover'	       => false,            // Boolean Pause the slideshow when hovering over slider, then resume when no longer hovering.
      'useCSS'	                 => true,	            // Boolean Slider will use CSS3 transitions, if available
      'touch'                    => true,             //	Boolean Allow touch swipe navigation of the slider on enabled devices
      'video'                    => false,	          // Boolean Will prevent use of CSS3 3D Transforms, avoiding graphical glitches
      'controlNav'           	 => true,             // Boolean Create navigation for paging control of each slide.
      'directionNav'           => true,            // Boolean Create previous/next arrow navigation.
      'prevText'	               => 'Previous',	    // String Set the text for the "previous" directionNav item
      'nextText'                => 'Next',	          // String Set the text for the "next" directionNav item
      'keyboard'                => true,            //	Boolean Allow slider navigating via keyboard left/right keys.
      'multipleKeyboard'    => false,            // 	Boolean Allow keyboard navigation to affect multiple sliders.
      'mousewheel'           => false,	          // Boolean (Dependency) Allows slider navigating via mousewheel
      'pausePlay'              => false,           // Boolean Create pause/play element to control slider slideshow.
      'pauseText'           	 => 'Pause',	        // String Set the text for the "pause" pausePlay item
      'playText'           	   => 'Play',	          // String Set the text for the "play" pausePlay item
      'controlsContainer'	   => ''	,                  // jQuery Object/Selector Container the navigation elements should be appended to.
      'manualControls'	     => '',                  // jQuery Object/Selector Define element to be used in lieu of dynamic controlNav.
      'sync'	           	         => '',                  // Selector Mirror the actions performed on this slider with another slider.
      'asNavFor'	           	   => ''	,                  // Selector Turn the slider into a thumbnail navigation for another slider.
      'itemWidth'           	 => 0	,                // 	Number Box-model width of individual carousel items, including horizontal borders and padding.
      'itemMargin'	           => 0	,                // 	Number Margin between carousel items.
      'minItems'           	   => 0	,                // 	Number Minimum number of carousel items that should be visible.
      'maxItems'           	 => 0	,                // 	Number Maximum number of carousel items that should be visible.
      'move'           	         => 0	,                // 	Number Number of carousel items that should move on animation.
      'thumbCaptions' => FALSE,
      'thumbCaptionsBoth' => FALSE,
    ];
  }

}
